---
version: "3.8"

services:

  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile.prod
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.local.win
    restart: unless-stopped

  nginx:
    build: ./nginx
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
        - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  static_volume: null