---
version: "3.8"

services:

  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile.prod
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.1-alpine
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
        - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data: null
  static_volume: null
