# Generated by Django 4.1.7 on 2023-04-13 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decimalnumber',
            name='number',
            field=models.CharField(help_text='Формат: 123456.789 или 123456.789-01', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Неверный формат номера', regex='^[0-9]{6}.[0-9]{3}(-[0-9]{2})?$')], verbose_name='Цифровая часть децимального номера'),
        ),
    ]
